---
title: "Vaccine Scheme Data"
format: html
---

```{r}
library(tidyverse)
library(lubridate)
library(readxl)
library(googlesheets4)
library(broom)
```

You can add options to executable code like this

```{r}
#| label: loading_in_data

library(readr)
Consolidated_QUANT_Vax_Cards_no_refuerzo_flu_vitA_A_B_Vax_Cards_MINUS_Refuerzos_HepBs_Varicella <- read_csv("Consolidated QUANT Vax Cards (no refuerzo, flu, vitA) - A+B Vax Cards MINUS Refuerzos, HepBs, Varicella.csv", 
    col_types = cols(date = col_date(format = "%d-%m-%y")))
#View(Consolidated_QUANT_Vax_Cards_no_refuerzo_flu_vitA_A_B_Vax_Cards_MINUS_Refuerzos_HepBs_Varicella)
```

```{r}
#| label: number_of_vaccines_received
vaccine_schedule <- Consolidated_QUANT_Vax_Cards_no_refuerzo_flu_vitA_A_B_Vax_Cards_MINUS_Refuerzos_HepBs_Varicella

  vaccine_final <- tibble(
  survey_date = vaccine_schedule$date,
  group_ID = vaccine_schedule$group,
  child_gender = vaccine_schedule$gender,
  child_dob = vaccine_schedule$dob,
  hep_b_status = ifelse(!is.na(vaccine_schedule$hep_b), "YES", "NO"),
  bcg_status = ifelse(!is.na(vaccine_schedule$bcg), "YES", "NO"),
  polio_vpi1_status = ifelse(!is.na(vaccine_schedule$polio_vpi1), "YES", "NO"),
  polio_vpi2_status = ifelse(!is.na(vaccine_schedule$polio_vpi2), "YES", "NO"),
  polio_vop1_status = ifelse(!is.na(vaccine_schedule$polio_vop1), "YES", "NO"),
  polio_vop2_status = ifelse(!is.na(vaccine_schedule$polio_vop2), "YES", "NO"),
  polio_vop3_status = ifelse(!is.na(vaccine_schedule$polio_vop3), "YES", "NO"),
  penta1_status = ifelse(!is.na(vaccine_schedule$penta1), "YES", "NO"),
  penta2_status = ifelse(!is.na(vaccine_schedule$penta2), "YES", "NO"),
  penta3_status = ifelse(!is.na(vaccine_schedule$penta3), "YES", "NO"),
  neumo1_status = ifelse(!is.na(vaccine_schedule$neumo1), "YES", "NO"),
  neumo2_status = ifelse(!is.na(vaccine_schedule$neumo2), "YES", "NO"),
  neumo3_status = ifelse(!is.na(vaccine_schedule$neumo3), "YES", "NO"),
  rota1_status = ifelse(!is.na(vaccine_schedule$rota1), "YES", "NO"),
  rota2_status = ifelse(!is.na(vaccine_schedule$rota2), "YES", "NO"),
  hep_a_status = ifelse(!is.na(vaccine_schedule$hep_a), "YES", "NO"),
  dpt1_status = ifelse(!is.na(vaccine_schedule$dpt1), "YES", "NO"),
  dpt2_status = ifelse(!is.na(vaccine_schedule$dpt2), "YES", "NO"),
  vph_1_status = ifelse(!is.na(vaccine_schedule$vph_1), "YES", "NO"),
  tetanus_dip_status = ifelse(!is.na(vaccine_schedule$tetanus_dip), "YES", "NO"))
```

```{r}
vaccine_final <- vaccine_final |>
  rowwise() |>
  mutate(yes_count = sum(c_across(hep_b_status:tetanus_dip_status) == "YES"))
print(vaccine_final)
```
